name: LiarGame
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: xcconfig/Project-Debug.xcconfig
  Release: xcconfig/Project-Release.xcconfig

options:
  indentWidth: 2
  tabWidth: 2

packages:
  Then:
    url: https://github.com/devxoul/Then
    version: 2.7.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    version: 6.5.0
  ReactorKit:
    url: https://github.com/ReactorKit/ReactorKit
    version: 3.2.0
  PinLayout:
    url: https://github.com/layoutBox/PinLayout
    version: 1.10.2
  FlexLayout:
    url: https://github.com/layoutBox/FlexLayout
    version: 1.3.24
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    version: 3.3.0

targets:
  GameBundle:
    type: application
    platform: iOS

    deploymentTarget: "13.0"

    configFiles:
      Debug: xcconfig/LiarGame-Debug.xcconfig
      Release: xcconfig/LiarGame-Release.xcconfig

    sources: [Targets/GameBundle]
    settings:
      base:
        INFOPLIST_FILE: Targets/GameBundle/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: Jay.LiarGameme

    dependencies:
      - target: LiarGame
      - target: RandomMusic
      - target: UtilKit
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: Lottie
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout

    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint
  LiarGame:
    type: framework.static
    platform: iOS
    deploymentTarget: "15.2"
    configFiles:
      Debug: xcconfig/LiarGame-Debug.xcconfig
      Release: xcconfig/LiarGame-Release.xcconfig
    info:
      path: Targets/LiarGame/Resources/Info.plist
    sources: [Targets/LiarGame]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: Jay.LiarGameme
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint
    dependencies:
      - target: UtilKit
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout

  RandomMusic:
    type: framework.static
    platform: iOS
    deploymentTarget: "15.2"
    info:
      path: Targets/RandomMusic/Resources/Info.plist
    configFiles:
      Debug: xcconfig/LiarGame-Debug.xcconfig
      Release: xcconfig/LiarGame-Release.xcconfig

    sources: [Targets/RandomMusic]

    settings:
      base:
        # INFOPLIST_FILE: LiarGame/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: Jay.LiarGameme

    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint

    dependencies:
      - target: UtilKit
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout
      - framework: frameworks/YouTubeiOSPlayerHelper.xcframework

  UtilKit:
    type: framework.static
    platform: iOS
    deploymentTarget: "15.2"
    configFiles:
      Debug: xcconfig/LiarGame-Debug.xcconfig
      Release: xcconfig/LiarGame-Release.xcconfig
    info:
      path: Targets/UtilKit/Resources/Info.plist
    sources: [Targets/UtilKit]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: Jay.LiarGameme
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint
    dependencies:
      - package: FlexLayout
